export const GET_ALL_CHATS_ERROR = 'GET_ALL_CHATS_ERROR'; 
export const GET_ALL_CHATS_REQUEST = 'GET_ALL_CHATS_REQUEST'; 
export const GET_ALL_CHATS_SUCCESS = 'GET_ALL_CHATS_SUCCESS'; 

export const JOIN_CHAT_ERROR = 'JOIN_CHAT_ERROR'; 
export const JOIN_CHAT_REQUEST = 'JOIN_CHAT_REQUEST'; 
export const JOIN_CHAT_SUCCESS = 'JOIN_CHAT_SUCCESS'; 

export const GET_CHAT_ERROR = 'GET_CHAT_ERROR'; 
export const GET_CHAT_REQUEST = 'GET_CHAT_REQUEST'; 
export const GET_CHAT_SUCCESS = 'GET_CHAT_SUCCESS'; 
