export const  GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const  GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const  GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR';

export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';
export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';